config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :links do
    get :new_link, on: :collection
  end

  root to: "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  # Relations
  has_many :taggings
  has_many :tags, through: :taggings

  belongs_to :user

  # Callbacks
  before_save :set_url
  
  def set_url
    if full_url
      uri = Addressable::URI.parse(full_url)
      self.url = uri&.host || '' + uri&.path || ''
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  # Relations 
  has_many :taggings
  has_many :links, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :link
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  require 'open_data/scraper'

  def load_tags_suggested(url)
    tags = Link.find_by(url: url)&.tags || []
    tags_selects = tags.map { |tag| [tag.name, tag.id] }
    tags_selects = tags_selects + ::OpenData::Scraper.new(@link.full_url).tags.map { |tag| [tag.name, ''] }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  def index
    @links = current_user.links
  end

  # GET /links/1
  def show
  end

  # GET /links/new
  def new
    @link = Link.new(link_params)
    @link.set_url

    load_tags
  end

  # POST /links
  def create
    @link = current_user.links.new(link_params)

    if @link.save
      create_tags
      redirect_to @link, notice: 'Link was successfully created.'
    else
      render :new
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  def new_link; end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:url, :full_url)
    end

    def create_tags
      if params[:url][:tags]
        params[:url][:tags].each do |tag|
          @link.tags << Tag.find_or_create_by(name: tag) if !tag.empty?
        end
      end
    end

    def load_tags
      @tags_selects = load_tags_suggested(@link.url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def tags(tags)
    tags_html = ''
    tags.each do |tag|
      tags_html = "<span class=\"label label-primary\">#{tag.name}</span>"
    end
    tags_html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Links</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <ul class="nav navbar-nav">
            <a class="navbar-brand" href="#">
              <li><%= link_to 'Links', links_path %></li>
            </a>
          </ul>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
            <a class="navbar-brand" href="#">
              <li><%= current_user.username %></li>
            </a>
            <a class="navbar-brand" href="#">
                <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
              </a>
            </ul>
          <% end %>
        </div>
      </nav>

      <%= yield %>
    <div>
  </body>
</html>

app/views/links/_form.html.slim
= form_for @link do |f|
  - if @link.errors.any?
    #error_explanation
      h2 = "#{pluralize(@link.errors.count, "error")} prohibited this link from being saved:"
      ul
        - @link.errors.full_messages.each do |message|
          li = message

  h3 = @link.full_url

  = f.hidden_field :url
  = f.hidden_field :full_url

  .field
    = f.label 'tags'
    = select  :url,
              :tags,
              options_for_select(@tags_selects),
              { },
              { class: 'form-control form-select', multiple: 'multiple' }

  .actions = f.submit

app/views/links/edit.html.slim
h1 Editing link

== render 'form'

=> link_to 'Show', @link
'|
=< link_to 'Back', links_path

app/views/links/index.html.slim
h1 Listing links

table.table
  thead
    tr
      th Url
      th Tags
      th
      th

  tbody
    - @links.each do |link|
      tr
        td = link.full_url
        td = tags(link.tags)
        td = link_to 'Show', link
        td = link_to 'Destroy', link, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Link', new_link_links_path, class: 'btn btn-primary'

app/views/links/new.html.slim
h1 New link

== render 'form'

= link_to 'Back', links_path

app/views/links/new_link.html.slim
= form_for Link.new, url: new_link_path, method: :get do |f|
  .field
    = f.label :full_url
    = f.text_field :full_url

  .actions = f.submit

app/views/links/show.html.slim
p#notice = notice

p
  strong Full url:
  = @link.full_url
p 
  strong tags:
  = tags(@link.tags)


= link_to 'Back', links_path, class: 'btn btn-default'